"""empty message

Revision ID: 09ba87b7cbb0
Revises: 
Create Date: 2020-08-03 09:19:37.795010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ba87b7cbb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LinRegResults',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('YearsExperience', sa.Float(), nullable=True),
    sa.Column('Prediction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LinRegResults')
    # ### end Alembic commands ###
