"""empty message

Revision ID: 29f10fb736f8
Revises: 09ba87b7cbb0
Create Date: 2020-08-03 10:46:07.550872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29f10fb736f8'
down_revision = '09ba87b7cbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lin_reg_results',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('YearsExperience', sa.Float(), nullable=True),
    sa.Column('Prediction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('LinRegResults')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LinRegResults',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"LinRegResults_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('YearsExperience', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Prediction', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='LinRegResults_pkey')
    )
    op.drop_table('lin_reg_results')
    # ### end Alembic commands ###
